### ISSUE TITLE
I created two repositories. please add

### ISSUE THREAD

**Issue by v5tech** [MaxChen/awesome-swift-and-tutorial-resources#2]
I  created two repositories
[awesome-ios-animation](https://github.com/sxyx2008/awesome-ios-animation) about iOS Animation Libraries.
[awesome-ios-chart](https://github.com/sxyx2008/awesome-ios-chart) about iOS Chart Libraries.
Thanks

**Comment by MaxChen** [comment]
Hi, I've added it. That's great.
Thanks !
