### ISSUE TITLE
Add: swift3-module-template

### ISSUE THREAD

**Issue by fulldecent** [MaxChen/awesome-swift-and-tutorial-resources#4]
Hello Max, would you consider to add this project. It is made to help people that will create Swift modules.

---
- [Swift 3 Module Template](https://github.com/fulldecent/swift3-module-template) - An opinionated starting point for awesome, reusable Swift 3 modules

---
- [Swift 3 Module 模仿](https://github.com/fulldecent/swift3-module-template) - 能帮你做最牛的 Swift 3 的 module

---

**Comment by fulldecent** [comment]
To be clear, are you still accepting contributions to this project? If so would a PR that fixes this be in scope to be merged?

**Comment by MaxChen** [comment]
Sorry for missing message, already added.
